name: Deploy TransactionService Backend

on:
  push:
    paths:
      - 'src/transactionservice/backend/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh ubuntu@$EC2_3.6.180.87 << 'EOF'
          cd /home/ubuntu/Weefly-Transactionservice/src/transactionservice/backend
          git pull origin main
          npm install
          pm2 restart transactionservice
        EOF
